apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris
  labels:
    app: iris
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: iris
  template:
    metadata:
      labels:
        app: iris
    spec:
      shareProcessNamespace: true
      containers:
      - name: iris
#        image: eu.gcr.io/hackathon-297608/myardyas-covid-19:b7cc362d6a252dc10cb4397566e936faec052ac3957cc8726402bda4bdaaeac6
        image: eu.gcr.io/hackathon-297608/myardyas-covid-19
        ports:
        - containerPort: 51773
        - containerPort: 52773
        - containerPort: 53773
        resources:
          requests:
            cpu: 300m
            memory: 1500Mi
          limits:
            cpu: 1000m
            memory: 1500Mi
