apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris
  labels:
    app: iris
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: iris
  template:
    metadata:
      labels:
        app: iris
    spec:
      shareProcessNamespace: true
      containers:
      - name: iris
        image: intersystemsdc/iris-community:2020.4.0.524.0-zpm
        ports:
        - containerPort: 51773
        - containerPort: 52773
        - containerPort: 53773
