apiVersion: v1
kind: Service
metadata:
  name: iris
  labels:
    app: iris
spec:
  type: LoadBalancer
  selector:
    app: iris
  ports:
  - name: "51773"
    port: 51773
    targetPort: 51773
  - name: "52773"
    port: 52773
    targetPort: 52773
  - name: "53773"
    port: 53773
    targetPort: 53773
